version: 0.0
os: linux
files:
  - source: /scripts
    destination: /home/ubuntu/scripts
hooks:
  AfterInstall:
    - location: /home/ubuntu/scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: /home/ubuntu/scripts/application_start.sh
      timeout: 300